### ISSUE TITLE
Version History Notes

### ISSUE THREAD

**Issue by jagrock** [AzureAD/MSAL.PS#14]
Is there any notes that describe the changes with each version?  Currently on 4.10.0.2 but not sure what changed between that version and the current version 4.16.0.2.

**Comment by jasoth** [comment]
I added the latest release to the Releases section of GitHub with a list of the latest changes. I will try to do this more going forward. Because the majority of the authentication logic is determined by the MSAL.net library. You will have to cross-reference that change log as well to understand the full set of changes.
https://github.com/AzureAD/MSAL.PS/releases
