### ISSUE TITLE
Get-MsalToken interactive fails on PowerShell 7

### ISSUE THREAD

**Issue by muzzar78** [AzureAD/MSAL.PS#18]
I have tried using Get-MsalToken -interactive in PowerShell 7.03 and PowerShell 7.1 preview 7 and it fails with the following error. 

![image](https://user-images.githubusercontent.com/13233154/93715135-c23cd480-fbaa-11ea-923f-341270d1d01e.png)

It launches the browser successfully and I can see the code is returned however the error is then returned. 
![image](https://user-images.githubusercontent.com/13233154/93715193-3a0aff00-fbab-11ea-8c50-a37f3b8eef5a.png)

When I run the same command from PowerShell 5.1 it completes successfully and I get the token back. Any help is appreciated.

**Comment by jasoth** [comment]
I am not sure why the behavior would be different between versions unless there is a difference in how the MSAL.net library works in .NET Framework vs Core but that does not appear to be the issue here.

If you follow the instructions in the error message you should be able to resolve this by making your app registration a public client. You are requesting a token for a public client, not a confidential client, because you are not providing an app secret or certificate as part of the authentication.
https://aka.ms/msal-net-invalid-client

**Comment by muzzar78** [comment]
@IpsitoDutta - I found the reason the interactive login wasn't working was the Azure AD app registration had the incorrect redirect URL. We were originally using localhost but when we change it to https://login.microsoftonline.com/common/oauth2/nativeclient then it worked as expected. 

![image](https://user-images.githubusercontent.com/13233154/139606249-c769fd1f-aace-492c-b712-0bf66fdf4562.png)

**Comment by IpsitoDutta** [comment]
So an update. I did have the redirect URI, but the platform chosen was web. After changing the platform to Mobile/Desktop app, I'm able to get the token issued but  Yammer is still not accepting it.

**Comment by IpsitoDutta** [comment]
Final update: After changing the platform to Mobile/Desktop and using the script below, I am able to call Yammer Rest APIs after a successful interactive auth:

$TenantId='<Tenant ID>'
$ClientId='<Client ID>'
$Scopes=@('https://api.yammer.com/.default')
$token=Get-MsalToken -TenantId $TenantId -ClientId $ClientId -Scopes $Scopes -Interactive
$Bearertoken="Bearer " + $token.Accesstoken
$headers = @{Authorization=$Bearertoken}
$response=Invoke-RestMethod -Method Get -Uri "https://www.yammer.com/api/v1/users/current.json” -Headers $headers
$response

Thank you for pointing me in the right direction. @muzzar78
