### ISSUE TITLE
Importing from Modules Gallery in Automation fails with message :While importing the module, an error occurred while processing the module content.

### ISSUE THREAD

**Issue by hakonKortvedt** [AzureAD/MSAL.PS#37]
Error importing the module MSAL.PS. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while processing the module content. Internal error message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.. at Orchestrator.Activities.SetModuleVersion.ExecuteInternal(CodeActivityContext context, String moduleName, ModuleLanguage moduleLanguage, String pythonModuleVersion, String modulePath, Guid accountId, Guid moduleVersionId, Int64 moduleContentByteSize, String storageUri, Int32 moduleVersion) at Orchestrator.Activities.SetModuleVersion.Execute(CodeActivityContext context) at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager) at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)

**Comment by sandytsang** [comment]
Same issues here, tested in two tenants. The older version of MSAL.PS module import works, but the newest version doesn't

**Comment by andersjulton** [comment]
Can confirm this. Manually importing it did not work either.

**Comment by andersjulton** [comment]
> I needed the module in my Azure Automation, so I ran this to save the older MSAL.PS module, then zip it, and import this older version to Azure Automation. The new version doesn't work.
> Save-Module -Name MSAL.PS -MaximumVersion 4.21.0.1 C:\Temp

Thanks @sandytsang, that worked for me.

**Comment by JankeSkanke** [comment]
Same issue here. There are other modules having dependencies on MSAL.PS as well that fails because of the this same issue. Importing from Azure Automation or clicking "Deploy to Azure Automation" in PSGallery gives the same error inside Azure Automation on the latest version. 
![image](https://user-images.githubusercontent.com/17491808/133634863-be34a7fa-ab38-4da4-a07e-4791d11bb45b.png)
This is the output from the deployment direct from PSGallery: 
![image](https://user-images.githubusercontent.com/17491808/133635123-ae5fcd6b-ec94-49a8-bd00-9155e92e3cc3.png)

**Comment by jasoth** [comment]
Thanks for reporting this. I will take a look. You can also download preview releases here: https://github.com/AzureAD/MSAL.PS/releases

**Comment by jasoth** [comment]
The bug should be fixed in the latest release. Thanks!
https://github.com/AzureAD/MSAL.PS/releases/tag/v4.36.1.0
